-- Escuelas
INSERT INTO `Escuelas` (`id`, `nombre`) VALUES
(301, 'Administracion'),
(201, 'Agronomia'),
(302, 'Antropologia'),
(101, 'Arquitectura'),
(303, 'Artes Especialidad de Musica'),
(304, 'Artes Especialidad de Plasticas'),
(305, 'Banca y Seguros'),
(202, 'Biologia'),
(102, 'Ciencias de la Computacion'),
(306, 'Ciencias de la Comunicacion Esp. Periodismo'),
(307, 'Ciencias de la Comunicacion Esp. Relaciones Publicas'),
(203, 'Ciencias de la Nutricion'),
(308, 'Contabilidad'),
(309, 'Derecho'),
(310, 'Economia'),
(204, 'Enfermeria'),
(311, 'Educacion'),
(312, 'Filosofia'),
(313, 'Finanzas'),
(103, 'Fisica'),
(314, 'Gestion de Empresas'),
(315, 'Gestion de Proyectos'),
(316, 'Gestion Publica'),
(317, 'Historia'),
(104, 'Ingenieria Ambiental'),
(105, 'Ingenieria Civil'),
(106, 'Ingenieria de Industrias Alimentarias'),
(107, 'Ingenieria de Materiales'),
(108, 'Ingenieria de Minas'),
(109, 'Ingenieria de Sistemas'),
(110, 'Ingenieria de Telecomunicaciones'),
(111, 'Ingenieria Electrica'),
(112, 'Ingenieria Electronica'),
(113, 'Ingenieria Geofisica'),
(114, 'Ingenieria Geologica'),
(115, 'Ingenieria Industrial'),
(116, 'Ingenieria Mecanica'),
(117, 'Ingenieria Metalurgica'),
(205, 'Ingenieria Pesquera'),
(118, 'Ingenieria Quimica'),
(119, 'Ingenieria Sanitaria'),
(318, 'Literatura y Linguistica'),
(319, 'Marketing'),
(120, 'Matematicas'),
(206, 'Medicina'),
(320, 'Psicologia'),
(121, 'Quimica'),
(321, 'Relaciones Industriales'),
(322, 'Sociologia'),
(323, 'Trabajo Social'),
(324, 'Turismo y Hoteleria');

-- Cursos
-- ??